#pragma once

// JetBrains Mono, converted to Adafruit-GFX bitmap fonts.
//
// Generated by tools/make_fonts.sh from the OFL-licensed JetBrains Mono Nerd
// Font, at codepoint range 0x20-0xFF. The range matters: the default 0x20-0x7E
// would reintroduce the tofu-box bug for accented artist names.
//
// LovyanGFX's GFXfont has a constexpr constructor in the same field order
// Adafruit emits, so the generated tables initialise as-is. GFXglyph's
// bitmapOffset is wider there (uint32_t vs uint16_t), which is a harmless
// widening of the generated values.

#include <M5Unified.h>

// The generated headers are written for AVR and tag their tables PROGMEM.
// Neither the host nor the ESP32 needs it.
#ifndef PROGMEM
#define PROGMEM
#endif

#include "JBMonoArtist.h"  // JetBrainsMonoNerdFont_Regular7pt8b
#include "JBMonoSmall.h"   // JetBrainsMonoNerdFont_Regular6pt8b
#include "JBMonoTitle.h"   // JetBrainsMonoNerdFont_Bold8pt8b
