#!/usr/bin/env python3
"""Convert the Daisy pixel-art GIFs into a generated C header.

The GIFs are 330x246 nearest-neighbour upscales of 55x41 pixel art (6px cells,
measured by cell-purity sweep — 55 columns scored 4% impure, every other grid
candidate 8-13%). This samples each cell's centre back down to the native grid
and stores 8-bit palette indices, so all ten animations cost ~90KB of flash and
the device can redraw them at any integer scale.

Index 0 is always the transparent key (the flat grey the sprites float on).

Usage: python3 tools/daisy_convert.py   (needs Pillow; writes src/ui/daisy/DaisyAssets.h)
"""

import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "ui", "daisy", "DaisyAssets.h")

COLS, ROWS = 55, 41
KEY = (150, 150, 155)  # background grey in every GIF

# name -> gif. Order matters: it defines the DaisyAnim enum.
ANIMS = [
    ("trot", "trot.gif"),
    ("zoomies", "zoomies.gif"),
    ("wag", "wag.gif"),
    ("sniff", "sniff.gif"),
    ("dig", "dig.gif"),
    ("sleep", "sleep.gif"),
    ("drowsy", "drowsy.gif"),
    ("yawn", "yawn.gif"),
    ("ask", "ask.gif"),
    ("alert", "alert.gif"),
]


def rgb565(c):
    r, g, b = c
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def downsample(frame):
    """Sample the centre of each 6px cell back to the 55x41 native grid."""
    rgb = frame.convert("RGB")
    w, h = rgb.size
    px = rgb.load()
    out = []
    for cy in range(ROWS):
        for cx in range(COLS):
            x = min(w - 1, int((cx + 0.5) * w / COLS))
            y = min(h - 1, int((cy + 0.5) * h / ROWS))
            out.append(px[x, y])
    return out


def close_to_key(c):
    return all(abs(c[i] - KEY[i]) <= 8 for i in range(3))


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    chunks = []
    table = []

    for name, gif in ANIMS:
        im = Image.open(os.path.join(ROOT, gif))
        n = getattr(im, "n_frames", 1)
        dur = int(im.info.get("duration", 200)) or 200

        palette = [None]  # slot 0: transparent
        frames = []
        for f in range(n):
            im.seek(f)
            cells = downsample(im)
            idxs = []
            for c in cells:
                if close_to_key(c):
                    idxs.append(0)
                    continue
                if c not in palette:
                    palette.append(c)
                idxs.append(palette.index(c))
            frames.append(idxs)

        if len(palette) > 256:
            sys.exit(f"{name}: palette overflow ({len(palette)})")

        pal_words = ", ".join(
            "0x0000" if c is None else f"0x{rgb565(c):04X}" for c in palette)
        chunks.append(
            f"static const uint16_t k_{name}_pal[{len(palette)}] = {{{pal_words}}};")
        for f, idxs in enumerate(frames):
            rows = []
            for y in range(ROWS):
                row = ", ".join(str(v) for v in idxs[y * COLS:(y + 1) * COLS])
                rows.append("    " + row)
            chunks.append(
                f"static const uint8_t k_{name}_f{f}[{COLS * ROWS}] = {{\n" +
                ",\n".join(rows) + "\n};")
        frame_list = ", ".join(f"k_{name}_f{f}" for f in range(n))
        chunks.append(
            f"static const uint8_t *const k_{name}_frames[{n}] = {{{frame_list}}};")
        table.append(
            f"    {{k_{name}_frames, k_{name}_pal, {len(palette)}, {n}, {dur}}},  // {name}")

    enum_names = ",\n  ".join(
        f"Daisy_{name.capitalize()} = {i}" for i, (name, _) in enumerate(ANIMS))

    header = f"""#pragma once

// GENERATED by tools/daisy_convert.py — do not edit by hand.
//
// Daisy the Bernese Mountain Dog, as 55x41 8-bit indexed pixel art. Palette
// index 0 is transparent. `const` data lands in flash on the ESP32, so none of
// this touches the heap.

#include <cstdint>

namespace daisy {{

constexpr int SPRITE_COLS = {COLS};
constexpr int SPRITE_ROWS = {ROWS};

enum DaisyAnim {{
  {enum_names},
  DaisyAnimCount = {len(ANIMS)}
}};

struct AnimData {{
  const uint8_t *const *frames;
  const uint16_t *palette;
  uint16_t palette_count;
  uint8_t frame_count;
  uint16_t frame_ms;
}};

{chr(10).join(chunks)}

static const AnimData ANIMS[DaisyAnimCount] = {{
{chr(10).join(table)}
}};

}}  // namespace daisy
"""
    with open(OUT, "w") as fh:
        fh.write(header)
    size = os.path.getsize(OUT)
    print(f"wrote {OUT} ({size // 1024}KB source)")


if __name__ == "__main__":
    main()
