#!/usr/bin/env python3
"""One-time Spotify OAuth handshake. Writes src/config/secrets.h.

Everything happens on this machine. Your client secret and refresh token are
read from the environment or typed at a hidden prompt, exchanged directly with
Spotify, and written straight to a gitignored header. They are never printed to
the terminal, never logged, and never leave your machine except to Spotify.

Setup, once:
  1. https://developer.spotify.com/dashboard -> Create app
  2. Redirect URI: http://127.0.0.1:8888/callback   (exactly this; Spotify's own
     example uses the loopback IP rather than "localhost")
  3. Copy the Client ID and Client Secret
  4. Run this script

Usage:
  python3 tools/get_refresh_token.py
  SPOTIFY_CLIENT_ID=... SPOTIFY_CLIENT_SECRET=... python3 tools/get_refresh_token.py
"""

import base64
import getpass
import http.server
import json
import os
import secrets
import sys
import threading
import urllib.error
import urllib.parse
import urllib.request
import webbrowser
from pathlib import Path

REDIRECT_URI = "http://127.0.0.1:8888/callback"
PORT = 8888
AUTH_URL = "https://accounts.spotify.com/authorize"
TOKEN_URL = "https://accounts.spotify.com/api/token"

SCOPES = [
    "user-read-playback-state",
    "user-modify-playback-state",
    "user-read-currently-playing",
    "user-library-read",
    "user-library-modify",
]

HEADER_TEMPLATE = """// Generated by tools/get_refresh_token.py. DO NOT COMMIT.
// This file is gitignored. It contains durable access to your Spotify account.
#pragma once

#define WIFI_SSID     "{wifi_ssid}"
#define WIFI_PASSWORD "{wifi_password}"

#define SPOTIFY_CLIENT_ID     "{client_id}"
#define SPOTIFY_CLIENT_SECRET "{client_secret}"
#define SPOTIFY_REFRESH_TOKEN "{refresh_token}"
"""


class CallbackHandler(http.server.BaseHTTPRequestHandler):
    result = {}
    done = threading.Event()

    def do_GET(self):  # noqa: N802
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path != "/callback":
            # Browsers routinely ask for /favicon.ico first; ignore anything
            # that is not the callback rather than consuming the wait.
            self.send_response(404)
            self.end_headers()
            return

        params = urllib.parse.parse_qs(parsed.query)
        CallbackHandler.result = {k: v[0] for k, v in params.items()}
        CallbackHandler.done.set()

        ok = "code" in CallbackHandler.result
        body = (
            b"<html><body style='font-family:system-ui;padding:3rem'>"
            b"<h2>Authorised.</h2><p>You can close this tab and return to the "
            b"terminal.</p></body></html>"
            if ok
            else b"<html><body style='font-family:system-ui;padding:3rem'>"
            b"<h2>Authorisation failed.</h2><p>Check the terminal.</p>"
            b"</body></html>"
        )
        self.send_response(200 if ok else 400)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        pass  # the default handler logs the full query string, code included


NO_TTY_MESSAGE = """\
error: no interactive terminal.

This script must run in a real terminal window (Terminal.app, iTerm, Ghostty),
NOT inside an agent/CI session. Without a TTY the prompt cannot hide what you
type, so your client secret would be echoed into whatever is capturing this
output — a chat transcript, a log file, CI output.

  cd {root}
  python3 tools/get_refresh_token.py

If you genuinely need it non-interactive, pass the values as environment
variables instead, and make sure your shell is not recording history:

  SPOTIFY_CLIENT_ID=... SPOTIFY_CLIENT_SECRET=... python3 tools/get_refresh_token.py
"""


def require_tty() -> None:
    if not sys.stdin.isatty():
        root = Path(__file__).resolve().parent.parent
        sys.exit(NO_TTY_MESSAGE.format(root=root))


def prompt_secret(env_name: str, label: str) -> str:
    val = os.environ.get(env_name)
    if val:
        return val.strip()
    require_tty()
    val = getpass.getpass(f"{label} (input hidden): ").strip()
    if not val:
        sys.exit(f"error: {label} is required")
    return val


def exchange(client_id: str, client_secret: str, code: str) -> dict:
    data = urllib.parse.urlencode(
        {
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": REDIRECT_URI,
        }
    ).encode()

    basic = base64.b64encode(f"{client_id}:{client_secret}".encode()).decode()
    req = urllib.request.Request(
        TOKEN_URL,
        data=data,
        headers={
            "Authorization": f"Basic {basic}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")
        sys.exit(f"error: token exchange failed ({e.code}): {detail}")


def main() -> int:
    client_id = prompt_secret("SPOTIFY_CLIENT_ID", "Spotify Client ID")
    client_secret = prompt_secret("SPOTIFY_CLIENT_SECRET", "Spotify Client Secret")

    state = secrets.token_urlsafe(16)
    query = urllib.parse.urlencode(
        {
            "client_id": client_id,
            "response_type": "code",
            "redirect_uri": REDIRECT_URI,
            "scope": " ".join(SCOPES),
            "state": state,
            "show_dialog": "false",
        }
    )
    auth_url = f"{AUTH_URL}?{query}"

    try:
        server = http.server.HTTPServer(("127.0.0.1", PORT), CallbackHandler)
    except OSError as e:
        sys.exit(f"error: cannot listen on 127.0.0.1:{PORT} ({e}). "
                 "Something else is using the port.")

    threading.Thread(target=server.serve_forever, daemon=True).start()

    print(f"\nOpening your browser to authorise. If it does not open:\n\n{auth_url}\n")
    webbrowser.open(auth_url)
    print("Waiting for the callback...")

    got_callback = CallbackHandler.done.wait(timeout=300)
    server.shutdown()

    result = CallbackHandler.result
    if not got_callback or not result:
        sys.exit("error: timed out waiting for the Spotify callback")
    if "error" in result:
        sys.exit(f"error: Spotify returned '{result['error']}'")
    if result.get("state") != state:
        sys.exit("error: state mismatch — aborting rather than trusting the callback")

    tokens = exchange(client_id, client_secret, result["code"])
    refresh_token = tokens.get("refresh_token")
    if not refresh_token:
        sys.exit("error: no refresh_token in the response")

    print("\nGot a refresh token.")

    wifi_ssid = os.environ.get("WIFI_SSID", "").strip()
    wifi_password = os.environ.get("WIFI_PASSWORD", "").strip()
    if not wifi_ssid and sys.stdin.isatty():
        print("WiFi details are only needed for the ESP32 build; Enter to skip.")
        wifi_ssid = input("WiFi SSID: ").strip()
        if wifi_ssid:
            wifi_password = getpass.getpass("WiFi password (input hidden): ").strip()

    out = Path(__file__).resolve().parent.parent / "src" / "config" / "secrets.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        HEADER_TEMPLATE.format(
            wifi_ssid=wifi_ssid,
            wifi_password=wifi_password,
            client_id=client_id,
            client_secret=client_secret,
            refresh_token=refresh_token,
        )
    )
    out.chmod(0o600)

    print(f"\nWrote {out}")
    print("It is gitignored. Do not paste its contents anywhere.")
    print("\nTo revoke later: https://www.spotify.com/account/apps/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
